# web配置------------------------------------------------------------------------------------------------------------------------------------------------
web:
  server:
    port: 8701

# service配置------------------------------------------------------------------------------------------------------------------------------------------------
service:
  server:
    port: 8601



from: from cloud param with webhook

