server:
  port: ${gateway.port:8503}
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.ip:localhost}:8501/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port} #eureka Status列显示的 实例ID
#    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
#    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
spring:
  application:
    name: acloud-gateway
  cloud:
    consul:
       host: ${consul_ip:172.25.16.46}
       port: 8500
       discovery:
         prefer-ip-address: true
         healthCheckPath: /actuator/health
         healthCheckInterval: 15s
         instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    gateway:
      discovery:
        locator:
          #服务发现组件结合,通过 serviceId 转发到具体的服务实例
          enabled: true
      routes:
        #网关路由USER-SERVICE服务,使用 Spring Cloud Gateway的默认路由规则大写的serviceId/**
      - id: cloud-simple-ui
        uri: lb://cloud-simple-ui
        predicates:
        - Path=/simple/**
        filters:
        - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: trace