image: gradle:4.9.0-jdk8-alpine

stages:
  - build
  - deploy

job_build:
  stage: build
  script:
    - mvn clean install
  tags:
    - gradletodocker

job_deploy:
  stage: deploy
  script:
    - echo "deploy over..."
  tags:
    - gradletodocker