spring:
  datasource:
    druid:
      #公共配置
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-idle: 10
      maxActive: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis:  60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery:  SELECT 1 FROM DUAL
      testWhileIdle:  true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize:  20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters:  stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000
      web-stat-filter:
      #是否启用StatFilter默认值true
        enabled: false
      stat-view-servlet:
      #是否启用StatViewServlet默认值true
        enabled: false
    #其中一个数据源，可以配置多个，对应多个config配置类
      base:
        url: jdbc:mysql://127.0.0.1:3306/summerdb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
        username: summer
        password: 123456

my:
  message: hello world cloud application